version: '3.8'

services:
  # 1. Message Broker
  my_rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  # 2. Người gửi đơn hàng
  producer:
    build: ./producer
    depends_on:
      - my_rabbitmq

  # 3. Người xử lý đơn hàng
  consumer:
    build: ./consumer
    depends_on:
      - my_rabbitmq