version: '3.8'

services:
  # Service 1: Server
  my_order_service:
    build: ./server
    ports:
      - "8080:5000"
    # THÊM ĐOẠN NÀY VÀO ĐÂY:
    volumes:
      - ./data:/app/data

  # Service 2: Client
  my_client:
    build: ./client
    depends_on:
      - my_order_service
    environment:
      - API_ENDPOINT=http://my_order_service:5000