version: '3.8'

services:
  #Service Database (Module 1 yêu cầu MySQL)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory_db
    ports:
      - "3306:3306"
    #Lệnh này tạo bảng tự động khi khởi chạy (Optional - để tiện test)
    command: --init-file /data/application/init.sql
    volumes:
       - ./init.sql:/data/application/init.sql

  #Service Adapter
  adapter:
    build: .
    depends_on:
      - db # Đảm bảo DB chạy trước Adapter
    volumes:
      # [QUAN TRỌNG - TỪ LAB 3 TASK 3.3]
      # Ánh xạ thư mục máy thật vào container để giả lập "Shared Folder"
      - ./input:/app/input
      - ./processed:/app/processed
    environment:
      - DB_HOST=db